[package]
name = "slitter"
version = "0.1.0"
authors = ["Paul Khuong <pkhuong@backtrace.io>"]
edition = "2018"

[dependencies]
lazy_static = "1"
smallvec = "1"
static_assertions = "1.1"

[build-dependencies]
cc = "1"

[dev-dependencies]
proptest = "1"
